p8105_hw2_dt2833
================
Dominique Tzou
2026-10-04

options(scipen=999) instructions: Read and clean the data; retain line,
station, name, station latitude / longitude, routes served, entry,
vending, entrance type, and ADA compliance. Convert the entry variable
from character (YES vs NO) to a logical variable (case_match function
may be useful).

Write a short paragraph about this dataset – explain briefly what
variables the dataset contains, describe your data cleaning steps so
far, and give the dimension (rows x columns) of the resulting dataset.
Are these data tidy?

Answer the following questions using these data:

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway;
125st Lenox); the distinct function may be useful here. How many
stations are ADA compliant? What proportion of station entrances / exits
without vending allow entrance? Reformat data so that route number and
route name are distinct variables. How many distinct stations serve the
A train? Of the stations that serve the A train, how many are ADA
compliant?

# Question 1

``` r
library(tidyverse)
```

    ## ── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
    ## ✔ dplyr     1.2.1     ✔ readr     2.2.0
    ## ✔ forcats   1.0.1     ✔ stringr   1.6.0
    ## ✔ ggplot2   4.0.3     ✔ tibble    3.3.1
    ## ✔ lubridate 1.9.5     ✔ tidyr     1.3.2
    ## ✔ purrr     1.2.2     
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()
    ## ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

``` r
library(dplyr)

transit_df = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
 na = c("NA", ".", ""))|>
janitor::clean_names() |>
select (line, station_name, station_latitude, station_longitude, route1,route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance_type, ada)|> 
  distinct() |>
  mutate(
    entry = recode_values(
      entry,
      "YES"  ~ 1,
      "NO" ~ 0
    )) #case_match()` was deprecated in dplyr 1.2.0.
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

**Description**

Dataset contains variables: line, station_name, station_latitude,
station_longitude, route1, route2, route3, route4, route5, route6,
route7, route8, route9, route10, route11, entry, vending, entrance_type,
ada. For data cleaning, we have cleaned names, selected our desired
variables, and standardized missing values to NA. This dataset contains
19 columns and 684 rows.

How many distinct stations are there? Note that stations are identified
both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway;
125st Lenox)? 472 unique stations

This dataset could be more “tidier”, the 11 route variable columns are
difficult to read

How many stations are ADA compliant? 84 What proportion of station
entrances / exits without vending allow entrance? 45/117 = 0.3846154

Reformat data so that route number and route name are distinct
variables. How many distinct stations serve the A train? 60 Of the
stations that serve the A train, how many are ADA compliant? 17

\#do i delete NA route name?

``` r
transit_distinct_df = 
  distinct(transit_df, station_name, line, .keep_all = TRUE) 

transit_distinct_df|> 
filter(ada ==TRUE) |> 
  nrow()
```

    ## [1] 84

``` r
n_distinct(pull(transit_df, station_name+line))
```

    ## [1] 472

``` r
# 472, not 465 
```

``` r
filter(transit_df,vending == "NO")|> 
  nrow() #117
```

    ## [1] 117

``` r
filter(transit_df,vending == "NO", entry == "1") |>
  nrow() #45
```

    ## [1] 45

``` r
#how many a train stations
transit_df |>
  mutate (
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
    ) |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number", 
    names_prefix = "route",
    values_to = "route_name") |>
  
filter(route_name=="A" )|>
 distinct( station_name, line, .keep_all = TRUE) |>
  nrow() #60
```

    ## [1] 60

``` r
#how many are ada compliant
transit_df |>
  mutate (
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
    ) |> 
  pivot_longer(
    route1:route11,
    names_to = "route_number", 
    names_prefix = "route",
    values_to = "route_name") |>
  
filter(route_name=="A" )|>
 distinct( station_name, line, .keep_all = TRUE) |>
filter(ada=="TRUE" )|>
nrow()
```

    ## [1] 17

\#Question 2

Importing data from Mr. Trash Wheel, Professor Trash Wheel, Gwynns Falls
Trash Wheel.

``` r
library(readxl)

mrtrash_df = read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet="Mr. Trash Wheel",  
             na = c("NA", ".", ""))|>
             janitor::clean_names() 
```

    ## New names:
    ## • `` -> `...15`
    ## • `` -> `...16`

``` r
proftrash_df = read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet="Professor Trash Wheel",
              na = c("NA", ".", ""))|>
             janitor::clean_names() 

gwynnstrash_df = read_excel("./data/202509 Trash Wheel Collection Data.xlsx", sheet="Gwynns Falls Trash Wheel",
              na = c("NA", ".", ""))|>
             janitor::clean_names()  
```

Cleaning Mr. Trash Wheel

``` r
mrtrash_df = 
  select(mrtrash_df,-x15, -x16)|>  #deleted unnecessary columns 
  filter (!is.na(dumpster)) |> #deleted non-dumpster specific data rows
  mutate(
        sports_balls = round(sports_balls), 
        sports_balls = as.integer(sports_balls), 
        trash_wheel = "Mr. Trash Wheel") |> # creating new variable to indicate wheel source of data 
  relocate(trash_wheel) 
```

Cleaning Professor Trash Wheel

``` r
proftrash_df =
  filter (proftrash_df, !is.na(dumpster)) |> #deleted non-dumpster specific data rows
  mutate(trash_wheel = "Professor Trash Wheel")  |> # creating new variable to indicate wheel source of data 
  relocate(trash_wheel) 
```

Cleaning Gwynns Falls Trash Wheel

``` r
gwynnstrash_df = 
  filter (gwynnstrash_df, !is.na(dumpster)) |> #deleted non-dumpster specific data rows
    mutate(trash_wheel = "Gwynns Falls Trash Wheel") |> # creating new variable to indicate wheel source of data 
  relocate(trash_wheel) 
```

Combining into 1 dataframe

``` r
str(mrtrash_df) # year variable needs to be converted to numeric to match other dataframes
```

    ## tibble [707 × 15] (S3: tbl_df/tbl/data.frame)
    ##  $ trash_wheel       : chr [1:707] "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" "Mr. Trash Wheel" ...
    ##  $ dumpster          : num [1:707] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:707] "May" "May" "May" "May" ...
    ##  $ year              : chr [1:707] "2014" "2014" "2014" "2014" ...
    ##  $ date              : POSIXct[1:707], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:707] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:707] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:707] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:707] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:707] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:707] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:707] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:707] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : int [1:707] 7 5 6 6 7 5 3 6 6 7 ...
    ##  $ homes_powered     : num [1:707] 0 0 0 0 0 0 0 0 0 0 ...

``` r
str(proftrash_df)
```

    ## tibble [132 × 14] (S3: tbl_df/tbl/data.frame)
    ##  $ trash_wheel       : chr [1:132] "Professor Trash Wheel" "Professor Trash Wheel" "Professor Trash Wheel" "Professor Trash Wheel" ...
    ##  $ dumpster          : num [1:132] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:132] "January" "January" "February" "February" ...
    ##  $ year              : num [1:132] 2017 2017 2017 2017 2017 ...
    ##  $ date              : POSIXct[1:132], format: "2017-01-02" "2017-01-30" ...
    ##  $ weight_tons       : num [1:132] 1.79 1.58 2.32 3.72 1.45 1.71 1.82 2.37 2.64 2.78 ...
    ##  $ volume_cubic_yards: num [1:132] 15 15 18 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles   : num [1:132] 1950 9540 8350 8590 7830 8210 9830 9240 9540 8230 ...
    ##  $ polystyrene       : num [1:132] 6080 11230 9210 1030 9950 ...
    ##  $ cigarette_butts   : num [1:132] 19700 17600 12000 13000 16000 14000 17000 15000 17000 13000 ...
    ##  $ glass_bottles     : num [1:132] 8 14 19 21 18 23 26 14 28 22 ...
    ##  $ plastic_bags      : num [1:132] 3100 5630 6430 5870 7450 ...
    ##  $ wrappers          : num [1:132] 15600 16700 12400 11030 15340 ...
    ##  $ homes_powered     : num [1:132] 29.8 26.3 38.7 62 24.2 ...

``` r
str(gwynnstrash_df)
```

    ## tibble [349 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ trash_wheel       : chr [1:349] "Gwynns Falls Trash Wheel" "Gwynns Falls Trash Wheel" "Gwynns Falls Trash Wheel" "Gwynns Falls Trash Wheel" ...
    ##  $ dumpster          : num [1:349] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:349] "July" "July" "July" "July" ...
    ##  $ year              : num [1:349] 2021 2021 2021 2021 2021 ...
    ##  $ date              : POSIXct[1:349], format: "2021-07-03" "2021-07-07" ...
    ##  $ weight_tons       : num [1:349] 0.93 2.26 1.62 1.76 1.53 2.06 1.9 2.16 2.6 3.21 ...
    ##  $ volume_cubic_yards: num [1:349] 15 15 15 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles   : num [1:349] 1200 2000 1800 1000 2100 2400 2700 3000 980 240 ...
    ##  $ polystyrene       : num [1:349] 360 240 270 180 240 360 320 320 180 42 ...
    ##  $ cigarette_butts   : num [1:349] 3400 3900 2900 2100 4000 3900 4200 4000 1800 400 ...
    ##  $ plastic_bags      : num [1:349] 1800 2200 2400 1800 2700 3000 3200 3600 1000 360 ...
    ##  $ wrappers          : num [1:349] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ homes_powered     : num [1:349] 15.5 37.7 27 29.3 25.5 ...

``` r
#converting 
mrtrash_df = 
  mutate(mrtrash_df, year = as.numeric(year))

#binding rows

trashwheels_df = 
  bind_rows(mrtrash_df, proftrash_df, gwynnstrash_df) |>
  janitor::clean_names() 
```

Write a paragraph about these data; you are encouraged to use inline R.
Be sure to note the number of observations in the resulting dataset, and
give examples of key variables. For available data, what was the total
weight of trash collected by Professor Trash Wheel? What was the total
number of cigarette butts collected by Gwynnda in June of 2022?

The trashwheel dataset contains data from three trash wheels: Mr. Trash
Wheel, Professor Trash Wheel and Gwynns Falls Trash Wheel. There is a
total of 1188 observations, 707 observations from Mr. Trash Wheel,132
observations from Professor Trash Wheel, and 349 observations from
Gwynns Falls Trash Wheel. This dataset includes information on types of
trash collected including, plastic_bottles, polystyrene,
cigarette_butts, glass_bottles, plastic_bags, wrappers, sports_balls,
while only sports ball data is only available for Mr. Trash Wheel. Other
details on collection include date, homes_powered, weight in tones and
volume in cubic yards.

The total weight of trash collected by Professor Trash Wheel is 282.26
tons.

The total number of cigarette butts collected by Gwynnda in June of 2022
is 18120
