---
title: "p8105_hw2_dt2833"
author: "Dominique Tzou"
date: "2026-10-04"
output: github_document
---

instructions: 
Read and clean the data; retain line, station, name, station latitude / longitude, routes served, entry, vending, entrance type, and ADA compliance. Convert the entry variable from character (YES vs NO) to a logical variable (case_match function may be useful).

Write a short paragraph about this dataset – explain briefly what variables the dataset contains, describe your data cleaning steps so far, and give the dimension (rows x columns) of the resulting dataset. Are these data tidy?

Answer the following questions using these data:

How many distinct stations are there? Note that stations are identified both by name and by line (e.g. 125th St 8th Avenue; 125st Broadway; 125st Lenox); the distinct function may be useful here.
How many stations are ADA compliant?
What proportion of station entrances / exits without vending allow entrance?
Reformat data so that route number and route name are distinct variables. How many distinct stations serve the A train? Of the stations that serve the A train, how many are ADA compliant?


# Question 1


```{r}
library(tidyverse)

transit_df = read_csv(file = "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
 na = c("NA", ".", ""))|>
janitor::clean_names() |>
select (line, station_name, station_latitude, station_longitude, route1,route2, route3, route4, route5, route6, route7, route8, route9, route10, route11, entry, vending, entrance_type, ada)|> 
  mutate(
    entry = recode_values(
      entry,
      "YES"  ~ 1,
      "NO" ~ 0
    )) #case_match()` was deprecated in dplyr 1.2.0.
```


__Description__

Dataset contains variables: `r names(transit_df)`. For data cleaning, we have cleaned names, selected our desired variables, and standardized missing values to NA. This dataset contains `r ncol(transit_df)` columns and `r nrow(transit_df)` rows. 

